#!/bin/bash
#BSUN -N

input_str=$1
cv_year=$2

module add R-4
module add gcc-8.3.0

mkdir -p /export/cluster-tmp/chenyehu

export TMPDIR=/export/cluster-tmp/chenyehu

Rscript --vanilla tmp.R $input_str $cv_year
