#!/bin/bash
input_str=$1
cv_year=$2
TYPE=$3

job_name=$TYPE$cv_year$input_str

#BSUB -o Senate.%J
#BSUB -R '(!gpu)'
#BSUN -N
#BSUB -J Senate

nlZs=$(Rscript --vanilla onejob.R $input_str $cv_year $TYPE)
echo $nlZs
