#!/bin/bash
#BSUB -o Senate.%J
#BSUB -R '(!gpu)'
#BSUN -N
#BSUB -J myjob

input_str=$1
cv_year=$2
TYPE=$3

module add R-4
module add gcc-8.3.0

TMPDIR=/export/cluster-tmp/

nlZs=$(Rscript --vanilla onejob.R $input_str $cv_year $TYPE)
echo $nlZs
