#!/bin/bash
declare -a input_strs=(0 7 14 21 28 42 56)
declare -a cv_years=(1992 1994 1996 1998 2000 2002 2004 2006 2008 2010 2012 2014 2016 2018)
declare -a TYPES=("GP" "LM")

mkdir -p nlZs

# declare -a input_strs=(0)
# declare -a cv_years=(2012)

number_file(){
    input_str=$1
    cv_year=$2
    TYPE=$3
    echo $(ls nlZs/"$TYPE"_"$cv_year"day"$input_str"* | wc -l)
}

one_job(){
    input_str=$1
    cv_year=$2
    TYPE=$3
    # echo $("./onerun $input_str $cv_year $TYPE")
    echo $(bsub -R '(!gpu) span[hosts=1]' -G SEAS-Lab-Garnett -o /home/research/chenyehu/log/Log."${input_str}_${cv_year}_${TYPE}" -J "${input_str}_${cv_year}_${TYPE}" "./onerun $input_str $cv_year $TYPE")
}

# for TYPE in ${TYPES[@]}; do
#     for input_str in ${input_strs[@]}; do
#         # bsub -R '(!gpu) span[hosts=1]' -G SEAS-Lab-Garnett "./matlabrun '$TYPE' $input_str"
#         for cv_year in ${cv_years[@]}; do
#             # for (( i=1; i<=$SEARCH_SIZE; i++ )) do 
#             #     nlZs=$(one_job $input_str $cv_year $TYPE $i)
# 	        #     echo $nlZs
#             # done
#     	    # nlZs=$(one_job $input_str $cv_year $TYPE)
# 	        # echo $nlZs
#             # n=$(number_file $input_str $cv_year $TYPE)
#             # if [ $n -lt 100 ]
#             # then
#             #     echo $TYPE $cv_year $input_str
#             # fi
#             # echo downloadresults/"LOO${TYPE}_${cv_year}day${input_str}_${best_cv_idx[i]}.csv"
            
#     	done
#         i=$((i+1))
#     done
# done

declare -a input_strs=(0 7 14 21 28 42 56)
declare -a cv_years=(2018)

for input_str in ${input_strs[@]}; do
    for cv_year in ${cv_years[@]}; do
        bsub -R '(!gpu) span[hosts=1]' -G SEAS-Lab-Garnett -J "${input_str}_${cv_year}" "./onerun $input_str $cv_year"
    done
done

