#!/bin/bash
input_strs=(0,7,14,28,42,90,120)
cv_years=(1992,1994,1996,1998,2000,2002,2004,2006,2008,2010,2012,2014,2016)
declare -a TYPES=("GP" "LM")

mkdir -p nlZs

one_job(){
    input_str=$1
    cv_year=$2
    TYPE=$3
    echo $(bsub -G SEAS-Lab-Garnett "./onerun $input_str $cv_year $TYPE")
}

for TYPE in ${TYPES[@]}; do
    for input_str in ${input_strs[@]}; do
        for cv_year in ${cv_years[@]}; do
    	    nlZs=$(one_job $input_str $cv_year $TYPE)
	    echo $nlZs
    	done
    done
done

