#!/bin/bash
declare -a input_strs=(0 7 14 21 28 42 56)
declare -a cv_years=(1992 1994 1996 1998 2000 2002 2004 2006 2008 2010 2012 2014 2016)
declare -a TYPES=("GP" "LM")

mkdir -p nlZs

# declare -a input_strs=(28)
# declare -a cv_years=(2014)

number_file(){
    input_str=$1
    cv_year=$2
    TYPE=$3
    echo $(ls nlZs/"$TYPE"_"$cv_year"day"$input_str"* | wc -l)
}

one_job(){
    input_str=$1
    cv_year=$2
    TYPE=$3
    # echo $("./onerun $input_str $cv_year $TYPE")
    echo $(bsub -R '(!gpu) span[hosts=1]' -G SEAS-Lab-Garnett "./onerun $input_str $cv_year $TYPE")
}

for TYPE in ${TYPES[@]}; do
    for input_str in ${input_strs[@]}; do
    bsub -G SEAS-Lab-Garnett "./matlabrun '$TYPE' '$input_str'"
        for cv_year in ${cv_years[@]}; do
    	    # nlZs=$(one_job $input_str $cv_year $TYPE)
	        # echo $nlZs
            # n=$(number_file $input_str $cv_year $TYPE)
            # if [ $n -lt 100 ]
            # then
            #     echo $TYPE $cv_year $input_str
            # fi
    	done
    done
done

